# Creating tensors with `tf.Variable`

In [7]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

In [9]:
#creating tf.constant(unchangable) and tf.Variable(changable)
changable_tensor=tf.Variable([2,5,6])
unchangabel_tensor=tf.constant([2,6,2])

In [13]:
changable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 5, 6], dtype=int32)>

In [15]:
#lets try to change one of the elements of the changable of tensor
changable_tensor[0]=[3]

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
#lets try to change one of the elements of the changabel tensor with .assign()
changable_tensor[0].assign(3)
print(changable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 5, 6], dtype=int32)>


In [18]:
#lets try to change the elements of unchangable tensor with .assign()
unchangabel_tensor[0].assign(33)
print(unchangable_tensor)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating RandomTensor with TensorFlow

In [24]:
#create random tensor
random_tensor=tf.random.normal(shape=(3,2))
print(random_tensor)

tf.Tensor(
[[ 0.7338968  -2.5268064 ]
 [-0.88726497 -1.6417441 ]
 [-1.3342372   0.01255416]], shape=(3, 2), dtype=float32)


In [29]:
#creating two random(but the same) tensor
random_1=tf.random.Generator.from_seed(43) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(43)
random_2=random_2.normal(shape=(3,2))
print(random_1)
print(random_2)
print(random_1==random_2)

tf.Tensor(
[[-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]
 [-0.7535805  -0.57166284]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]
 [-0.7535805  -0.57166284]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


# Shuffle the order of elements in the tensor `tf.random.shuffle`

#### In machine learning / deep learning, we often shuffle data before training because:

### 1.Avoids learning order bias
##### If the data is ordered (for example, all class A samples first, then all class B), the model might start learning patterns that depend on the order instead of the actual data relationships.

### 2.Improves generalization
##### Shuffling makes the model see a more random mix of examples, helping it generalize better and not overfit to a particular sequence.

### 3.Ensures better gradient updates
##### During mini-batch training, random batches created from shuffled data give more diverse gradients, leading to smoother and faster convergence.

In [ ]:
random_3=tf.constant([[3,5,6],[2,1,2],[3,5,6],[9,0,3]])
print('original matrix is')
print(random_3)
print('shuffled of matrix is :')
print(tf.random.shuffle(random_3))

original matrix is
tf.Tensor(
[[3 5 6]
 [2 1 2]
 [3 5 6]
 [9 0 3]], shape=(4, 3), dtype=int32)
shuffled of matrix is :
tf.Tensor(
[[9 0 3]
 [3 5 6]
 [2 1 2]
 [3 5 6]], shape=(4, 3), dtype=int32)
