#### creating tensors with numpy array

In [1]:
import tensorflow as tf
import warnings 
warnings.filterwarnings('ignore')

2025-10-10 12:11:59.488240: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-10 12:12:19.900449: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-10 12:12:33.290251: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [2]:
#creating tensors with all one
tf.ones(shape=(3,5),dtype='int32')

2025-10-10 12:12:49.391166: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [3]:
#creating tensors with all zeros
tf.zeros(shape=(3,3),dtype='int32')

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

#### the main difference between numpy array and tensorflow tensor is tensor can be runs on GPU(which is faster for computing)

#### converting numpy array into tensors

In [4]:
import numpy as np
array_A=np.arange(1,28) # numpy array
array_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [5]:
tf.constant(array_A,shape=(3,3,3)) #converting numpy array into tensors

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [6]:
#create a rank 4 tensor(4 dimensions)
rank_4_tensors=tf.ones(shape=(2,3,4,5))
rank_4_tensors


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

# Creating,Expanding and Indexing Tensors

In [60]:
rank_four_tensors=tf.constant([[[
    
    [1,2,5,4,6],
    [2,4,6,2,6],
    [2,5,4,6,6],
    [3,2,6,2,2]],
    
    [[3,7,2,7,3],
    [3,7,3,7,3],
    [3,7,3,2,7],
    [3,7,3,2,3]],

    [[2,7,3,7,3],
     [3,7,3,2,7],
     [1,7,3,7,3],
     [2,7,8,4,3]]],

    [[[1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.]],

    [[1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1.]],

    [[1., 1., 1., 1., 9.],
    [1., 1., 1., 1., 1.],
    [1., 1., 5., 1., 1.],
    [1., 1., 1., 1., 1.]]]])





So it’s a 4D tensor with:

* 2 blocks

* each block has 3 matrices

* each matrix is 4X5

In [46]:
rank_four_tensors.shape,rank_four_tensors.ndim

(TensorShape([2, 3, 4, 5]), 4)

In [47]:
rank_four_tensors[0] #first block

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 2., 5., 4., 6.],
        [2., 4., 6., 2., 6.],
        [2., 5., 4., 6., 6.],
        [3., 2., 6., 2., 2.]],

       [[3., 7., 2., 7., 3.],
        [3., 7., 3., 7., 3.],
        [3., 7., 3., 2., 7.],
        [3., 7., 3., 2., 3.]],

       [[2., 7., 3., 7., 3.],
        [3., 7., 3., 2., 7.],
        [1., 7., 3., 7., 3.],
        [2., 7., 8., 4., 3.]]], dtype=float32)>

In [48]:
rank_four_tensors[0,1] #second matrix of first block

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[3., 7., 2., 7., 3.],
       [3., 7., 3., 7., 3.],
       [3., 7., 3., 2., 7.],
       [3., 7., 3., 2., 3.]], dtype=float32)>

In [49]:
rank_four_tensors[0,0,0] #first row of first matrix of first block

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 5., 4., 6.], dtype=float32)>

In [50]:
print(rank_four_tensors[0,1,0]) #first row of second matrix of first block
print(rank_four_tensors[0,1,2]) #third row of second matrix of first block

tf.Tensor([3. 7. 2. 7. 3.], shape=(5,), dtype=float32)
tf.Tensor([3. 7. 3. 2. 7.], shape=(5,), dtype=float32)


In [51]:
print(rank_four_tensors[0,1,0,0]) #first elements of first row of second matrix of first block
print(rank_four_tensors[0,1,3,3]) #third elements of last row of second matrix of first block

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [ ]:
print(rank_four_tensors[1,2]) # third matrix of second block
print(rank_four_tensors[1,2,2]) #third row of third matrix of second block
print(rank_four_tensors[1,2,0,4]) #fourth element of first row of third matrix of second block

tf.Tensor(
[[1. 1. 1. 1. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(4, 5), dtype=float32)
tf.Tensor([1. 1. 5. 1. 1.], shape=(5,), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)


In [82]:
#get various attributes of the tensors
print('the data types of tensors is :',rank_four_tensors.dtype)
print('the dimensions of the tensors is :',rank_four_tensors.ndim)
print('the shape of the tensors is :',rank_four_tensors.shape)
print('element along the 0 axis is:',rank_four_tensors.shape[0])
print('element along the last axis is:',rank_four_tensors.shape[-1])
print('the total number of elements in the tensors is:',tf.size(rank_four_tensors))
print('the total number of elements in the tensors is:',tf.size(rank_four_tensors).numpy())



the data types of tensors is : <dtype: 'float32'>
the dimensions of the tensors is : 4
the shape of the tensors is : (2, 3, 4, 5)
element along the 0 axis is: 2
element along the last axis is: 5
the total number of elements in the tensors is: tf.Tensor(120, shape=(), dtype=int32)
the total number of elements in the tensors is: 120


In [83]:
# get the first three elements from each dimensions
rank_four_tensors[:3,:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[1., 2., 5.],
         [2., 4., 6.],
         [2., 5., 4.]],

        [[3., 7., 2.],
         [3., 7., 3.],
         [3., 7., 3.]],

        [[2., 7., 3.],
         [3., 7., 3.],
         [1., 7., 3.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 5.]]]], dtype=float32)>

In [ ]:
rank_four_tensors[:1] #first block

<tf.Tensor: shape=(1, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 2., 5., 4., 6.],
         [2., 4., 6., 2., 6.],
         [2., 5., 4., 6., 6.],
         [3., 2., 6., 2., 2.]],

        [[3., 7., 2., 7., 3.],
         [3., 7., 3., 7., 3.],
         [3., 7., 3., 2., 7.],
         [3., 7., 3., 2., 3.]],

        [[2., 7., 3., 7., 3.],
         [3., 7., 3., 2., 7.],
         [1., 7., 3., 7., 3.],
         [2., 7., 8., 4., 3.]]]], dtype=float32)>

In [ ]:
rank_four_tensors[:1,:1] #first block first matrix

<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[1., 2., 5., 4., 6.],
         [2., 4., 6., 2., 6.],
         [2., 5., 4., 6., 6.],
         [3., 2., 6., 2., 2.]]]], dtype=float32)>

In [ ]:
rank_four_tensors[:1,:1,:1] # first row of first block of first matrix

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 2., 5., 4., 6.]]]], dtype=float32)>

In [ ]:
rank_four_tensors[:1,:1,:1,:3] #beginning three elements of first row of first block of first matrix

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[1., 2., 5.]]]], dtype=float32)>

In [ ]:
rank_four_tensors[:1,:1,:,-1] # last item of each row of the first row of first block of first matrix

<tf.Tensor: shape=(1, 1, 4), dtype=float32, numpy=array([[[6., 6., 6., 2.]]], dtype=float32)>

In [109]:
rank_two_tensors=tf.constant([[1,6,3],[4,7,9]])
rank_two_tensors

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 6, 3],
       [4, 7, 9]], dtype=int32)>

In [110]:
print('dimension of the tensors is :',rank_two_tensors.ndim)

dimension of the tensors is : 2


# add the extra dimensions by `tf.newaxis`

In [114]:
rank_three_tensors=rank_two_tensors[...,tf.newaxis]
print(rank_three_tensors)
print('the dimensions of the rank_three_tensors',rank_three_tensors.ndim)
print('the shape of the rank_three_tensors',rank_three_tensors.shape)

tf.Tensor(
[[[1]
  [6]
  [3]]

 [[4]
  [7]
  [9]]], shape=(2, 3, 1), dtype=int32)
the dimensions of the rank_three_tensors 3
the shape of the rank_three_tensors (2, 3, 1)


# Alternatives of the tf.newaxis `tf.expand_dims`

In [ ]:
tf.expand_dims(rank_two_tensors,axis=-1) # -1 means expand the final axis  

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [6],
        [3]],

       [[4],
        [7],
        [9]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_two_tensors,axis=1) # add new dimensions  in  the middle

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 6, 3]],

       [[4, 7, 9]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_two_tensors,axis=0) #add new dimensions in the beginning

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 6, 3],
        [4, 7, 9]]], dtype=int32)>