# Manipulating Tensors With Basic Opearations
* basic operation like `+`,`-`,`*`

### Addition Opearation

In [3]:
# you can add value to the tensors using the addition operator
import tensorflow as tf
tensor=tf.constant([[2,6,3],[3,6,5]])
print(tensor)
tensor_updated=tensor+10
print('tensor after the addition is:',tensor)

tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
tensor after the addition is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)


In [4]:
#the original tensor is unchanged 
print(tensor)

tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)


### Subtraction operation

In [6]:
subtract=tf.constant([[2,4,6],[4,6,3]])
subtracted_tensor=tensor-subtract
print('the original tensor is :',tensor)
print('the tensor to be subtracted is:',subtract)
print('the result after the subtraction is:',subtracted_tensor)

the original tensor is : tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor to be subtracted is: tf.Tensor(
[[2 4 6]
 [4 6 3]], shape=(2, 3), dtype=int32)
the result after the subtraction is: tf.Tensor(
[[ 0  2 -3]
 [-1  0  2]], shape=(2, 3), dtype=int32)


### Multiplication Opearation by `tf.multiply()`
* this is element wise multiplication not matrix multiplication

In [17]:
print('the original tensor is:',tensor)
print('the tensor after multiplication by 10 is:',tensor*10)

the original tensor is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor after multiplication by 10 is: tf.Tensor(
[[20 60 30]
 [30 60 50]], shape=(2, 3), dtype=int32)


In [14]:
multiply_matrix=tf.constant([[2,6,6],[3,7,6]])
print('the original tensor is:',tensor)
print('the tensor to be multiplied is:',multiply_matrix)
print('the result after the multiplication is:',tf.multiply(tensor,multiply_matrix))

the original tensor is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor to be multiplied is: tf.Tensor(
[[2 6 6]
 [3 7 6]], shape=(2, 3), dtype=int32)
the result after the multiplication is: tf.Tensor(
[[ 4 36 18]
 [ 9 42 30]], shape=(2, 3), dtype=int32)


* in `tf.multiply()` TensorFlow allows you to multiply two tensors of the same shape (or broadcastable shapes) element by element:
* This is valid because the shapes are identical: both (2, 3).


In [ ]:
[[2*2, 6*6, 3*6],
 [3*3, 6*7, 5*6]]

[[4, 36, 18], [9, 42, 30]]

### Matrix  Multiplication Opearation by `tf.matmul()`
* this is real matrix multiplication where order of (mxn) and (pxq)
* n and p must be equal
* the resultant matrix is order of (mxq)

In [16]:
real_mult=tf.constant([[3,6,6],[3,8,3],[3,7,5]])
print('the original tensor is:',tensor)
print('the tensor to be multiplied is:',real_mult)
print('the result after matrix multiplication is:',tf.matmul(tensor,real_mult))

the original tensor is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor to be multiplied is: tf.Tensor(
[[3 6 6]
 [3 8 3]
 [3 7 5]], shape=(3, 3), dtype=int32)
the result after matrix multiplication is: tf.Tensor(
[[ 33  81  45]
 [ 42 101  61]], shape=(2, 3), dtype=int32)


### Matrix Multiplication With The Help Of `tf.transpose()`

In [18]:
tensor1=tf.constant([[3,5,6],[3,6,7]])
print('the original tensor is:',tensor)
print('the tensor to be multiplied is:',tensor1)
print('the matrix multiplication is:',tf.matmul(tensor,tensor1))

the original tensor is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor to be multiplied is: tf.Tensor(
[[3 5 6]
 [3 6 7]], shape=(2, 3), dtype=int32)


2025-10-11 03:38:57.696287: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3]


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul] name: 

* we are encountering the above error because the order/shape of first tensor is (2x3) and second tensor is (2x3)
* i.e 3 and 2 is not equal
* Now we can solve this by the help of `tf.transpose()`

In [20]:
tensor1=tf.constant([[3,5,6],[3,6,7]])
tensor1_transpose=tf.transpose(tensor1)
print('the original tensor is:',tensor)
print('the tensor to be multiplied is:',tensor1)
print('the tensor1 matrix after the transpose is:',tensor1_transpose)
print('the matrix multiplication is:',tf.matmul(tensor,tensor1_transpose))

the original tensor is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor to be multiplied is: tf.Tensor(
[[3 5 6]
 [3 6 7]], shape=(2, 3), dtype=int32)
the tensor1 matrix after the transpose is: tf.Tensor(
[[3 3]
 [5 6]
 [6 7]], shape=(3, 2), dtype=int32)
the matrix multiplication is: tf.Tensor(
[[54 63]
 [69 80]], shape=(2, 2), dtype=int32)


### Matrix Multiplication with the help of `tf.tensordot()`
* Tensordot (also known as tensor contraction) sums the product of elements from a and b over the indices specified by axes.
* Example 1: When a and b are matrices (order 2), the case axes=1 is equivalent to matrix multiplication.
* Example 2: When a and b are matrices (order 2), the case axes = [[1], [0]] is equivalent to matrix multiplication.
* Example 3: When a and b are matrices (order 2), the case axes=0 gives the outer product, a tensor of order 4.

In [ ]:
# when axes is 1
print('the original marix is:',tensor)
print('the matrix to be multiplied is:',tensor1_transpose)
print('the matrix multiplication is:',tf.tensordot(tensor,tensor1_transpose,axes=1))

the original marix is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the matrix to be multiplied is: tf.Tensor(
[[3 3]
 [5 6]
 [6 7]], shape=(3, 2), dtype=int32)
the matrix multiplication is: tf.Tensor(
[[54 63]
 [69 80]], shape=(2, 2), dtype=int32)


In [ ]:
# when axes is 0
print('the original marix is:',tensor)
print('the matrix to be multiplied is:',tensor1_transpose)
print('the matrix multiplication is:',tf.tensordot(tensor,tensor1_transpose,axes=0))

the original marix is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the matrix to be multiplied is: tf.Tensor(
[[3 3]
 [5 6]
 [6 7]], shape=(3, 2), dtype=int32)
the matrix multiplication is: tf.Tensor(
[[[[ 6  6]
   [10 12]
   [12 14]]

  [[18 18]
   [30 36]
   [36 42]]

  [[ 9  9]
   [15 18]
   [18 21]]]


 [[[ 9  9]
   [15 18]
   [18 21]]

  [[18 18]
   [30 36]
   [36 42]]

  [[15 15]
   [25 30]
   [30 35]]]], shape=(2, 3, 3, 2), dtype=int32)


### Matrix Multiplication with the help of `tf.reshape`
* here we reshape the matrix order which are incompatible for matrix multiplication
* in below code both tensor and tensor1 have same shape i.e(2,3)
* so it is impossible to Matrix Multiplication
* now we reshape the tensor1 to shape (3,2)

In [26]:
print('the original tensor is:',tensor)
print('the tensor to be mutiplied is:',tensor1)
print('the matrix multiplication is:',tf.matmul(tensor,tf.reshape(tensor1,shape=(3,2))))

the original tensor is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the tensor to be mutiplied is: tf.Tensor(
[[3 5 6]
 [3 6 7]], shape=(2, 3), dtype=int32)
the matrix multiplication is: tf.Tensor(
[[60 49]
 [75 68]], shape=(2, 2), dtype=int32)


### Matrix Multipication with the help of `@` operator

In [32]:

print('the original marix is:',tensor)
print('the matrix to be multiplied is:',tensor1_transpose)
print('the matrix multiplication is:',(tensor@tensor1_transpose))

the original marix is: tf.Tensor(
[[2 6 3]
 [3 6 5]], shape=(2, 3), dtype=int32)
the matrix to be multiplied is: tf.Tensor(
[[3 3]
 [5 6]
 [6 7]], shape=(3, 2), dtype=int32)
the matrix multiplication is: tf.Tensor(
[[54 63]
 [69 80]], shape=(2, 2), dtype=int32)


### The difference between `tf.transpose()` and `tf.reshape()`
* `tf.transpose()` :Rearranges the axes (dimensions) of a tensor.
* `tf.transpose()`: It does not change the number of elements or how they’re grouped in memory — it just swaps dimensions (like rows ↔ columns).

* `tf.reshape()`:Changes the shape (layout) of the tensor by rearranging elements.
* `tf.reshape()`:It does not move data between axes — it just reinterprets the same elements into a new shape (as long as total elements match).

In [31]:
print('the original tensor is:',tensor1)
print('the tensor after the transpose is:',tf.transpose(tensor1))
print('the tensor after the reshape is:',tf.reshape(tensor1,shape=(3,2)))

the original tensor is: tf.Tensor(
[[3 5 6]
 [3 6 7]], shape=(2, 3), dtype=int32)
the tensor after the transpose is: tf.Tensor(
[[3 3]
 [5 6]
 [6 7]], shape=(3, 2), dtype=int32)
the tensor after the reshape is: tf.Tensor(
[[3 5]
 [6 3]
 [6 7]], shape=(3, 2), dtype=int32)


### Conclusion: While the matrix multiplication we always use `tf.transpose()` if one of the matrix don't have suitable shape for multiplication and don't use `tf.reshape()`