# Introduction To TensorFlow

In [10]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf
print(tf.__version__)

2.20.0


In [11]:
#create a tensor with tf.constant()
scalar=tf.constant(99)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [12]:
#check the number of dimension of tensor
scalar.ndim

0

In [22]:
#create a vector and check the dimension 
vector=tf.constant([2,5,6,8])
print(vector)
print('the dimension of vector is :',vector.ndim)

tf.Tensor([2 5 6 8], shape=(4,), dtype=int32)
the dimension of vector is : 1


In [21]:
#create a matrix and check the dimension of matrix
matrix=tf.constant([[1,2,4],
                    [9,8,6]])
print(matrix)
print('the dimension of matrix is :',matrix.ndim)

tf.Tensor(
[[1 2 4]
 [9 8 6]], shape=(2, 3), dtype=int32)
the dimension of matrix is : 2


In [20]:
#create a tensor
tensor=tf.constant([[[1,3,5],[3,6,7]],
                    [[2,5,6],[3,6,7]],
                    [[4,6,7],[6,7,7]]])
print(tensor)
print('the dimension of tensor is :',tensor.ndim)

tf.Tensor(
[[[1 3 5]
  [3 6 7]]

 [[2 5 6]
  [3 6 7]]

 [[4 6 7]
  [6 7 7]]], shape=(3, 2, 3), dtype=int32)
the dimension of tensor is : 3
