### Changing the dtypes of the tensor

In [3]:
# create a new tensors with default dtypes
import tensorflow as tf
b=tf.constant([2.2,3.6,6.7])
b,b.dtype

2025-10-11 09:50:13.460771: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-11 09:50:13.507477: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-11 09:50:15.728111: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-11 09:50:18.208425: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.2, 3.6, 6.7], dtype=float32)>,
 tf.float32)

In [4]:
# change from float32 to float16(reduced precision)
d=tf.cast(b,dtype=tf.float16)
d,d.dtype

(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2.2, 3.6, 6.7], dtype=float16)>,
 tf.float16)

In [5]:
c=tf.constant([[9,8,6],[8,6,5]])
c,c.dtype

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[9, 8, 6],
        [8, 6, 5]], dtype=int32)>,
 tf.int32)

In [6]:
#change from int32 to int16(reduced precision)
e=tf.cast(c,dtype=tf.int16)
e,e.dtype

(<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
 array([[9, 8, 6],
        [8, 6, 5]], dtype=int16)>,
 tf.int16)

### Aggregations of Tensors
* Aggregating tensors = combining many elements into fewer by using reduction operations like sum, mean, max, or min.

In [7]:
#get the absolute value of the tensors
D=tf.constant([-3,-4,7])
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 7], dtype=int32)>

In [8]:
# create a random tensor with value between 0 and 100 of size 50
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([97, 26, 90, 17, 31, 96, 32,  8, 74, 37, 34, 29, 34,  7, 71, 24, 16,
       16, 77, 42,  5,  5, 17, 21, 91, 22, 47, 44, 89, 11, 90, 44,  3, 26,
       64, 92, 12, 78, 22, 24,  9, 59, 41, 80, 74, 18, 92, 86, 92, 53])>

In [9]:
print('the shape of the tensors is:',E.shape)
print('the size of the tensors is:',tf.size(E))
print('the dimensions of the tensors is:',E.ndim)

the shape of the tensors is: (50,)
the size of the tensors is: tf.Tensor(50, shape=(), dtype=int32)
the dimensions of the tensors is: 1


In [10]:
#to find the minimum item from the tensors
print('the minimum item from the tensors is:',tf.reduce_min(E))

the minimum item from the tensors is: tf.Tensor(3, shape=(), dtype=int64)


In [11]:
tensors=tf.constant([[3,5,6],[3,5,-1]])
tensors

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  5,  6],
       [ 3,  5, -1]], dtype=int32)>

In [12]:
print('the greatest items from the tensors is:',tf.reduce_max(tensors))
print('the minimum items form the tensors is:',tf.reduce_min(tensors))
print('the total sum of items of tensors is:',tf.reduce_sum(tensors))
print('the total sum along row wise is:',tf.reduce_sum(tensors,axis=0))
print('the total sum along the columns wise is:',tf.reduce_sum(tensors,axis=1))

the greatest items from the tensors is: tf.Tensor(6, shape=(), dtype=int32)
the minimum items form the tensors is: tf.Tensor(-1, shape=(), dtype=int32)
the total sum of items of tensors is: tf.Tensor(21, shape=(), dtype=int32)
the total sum along row wise is: tf.Tensor([ 6 10  5], shape=(3,), dtype=int32)
the total sum along the columns wise is: tf.Tensor([14  7], shape=(2,), dtype=int32)


### finding the variance and the standard deviation of the tensors
* Variance=1\n​∑(xi​−mean)2
* Standard Deviation=sqrt(Variance)
​

In [25]:

variance=tf.math.reduce_variance(tf.cast(tensors,dtype='float32')).numpy()
standard_deviation=tf.math.reduce_std(tf.cast(tensors,dtype='float32')).numpy()
print('the variance of the tensors is:',variance)
print('the standard deviation of the tensors is:',standard_deviation)

the variance of the tensors is: 5.25
the standard deviation of the tensors is: 2.291288


### finding the positional maximum and minimum of a tensor

In [2]:
import tensorflow as tf
tf.random.set_seed(43)
item=tf.random.uniform(shape=[50])
item

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

In [3]:
# find the postional maximum
print('the index for the greatest element is:',tf.argmax(item).numpy())
print('so the greatest element is:',item[37].numpy())

the index for the greatest element is: 37
so the greatest element is: 0.99417937


In [4]:
# find the positional minimum
print('the index for the smallest element is:',tf.argmin(item).numpy())
print('so the smallest element is:',item[tf.argmin(item).numpy()].numpy())

the index for the smallest element is: 32
so the smallest element is: 0.0015381575


### Sqeezing the tensor(removing all the single dimensions)
* Squeezing a tensor means removing dimensions with size 1 from its shape.
* It doesn’t change the actual data — it only changes the shape (i.e., how the data is arranged).

In [19]:
# lets create the tensors to get started
tf.random.set_seed(99)
tensors_1=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
print(tensors_1)
print('the shape of the tensors is:',tensors_1.shape)
print('the dimensions of the tensors is:',tensors_1.ndim)

tf.Tensor(
[[[[[8.39977026e-01 6.16283536e-01 8.56459022e-01 1.86221480e-01
     3.53955030e-02 9.65633988e-01 5.95039606e-01 7.78796554e-01
     2.20869184e-01 8.08609366e-01 2.16290355e-01 5.07235289e-01
     2.81568289e-01 4.80004430e-01 4.65334892e-01 7.84289122e-01
     5.13068557e-01 3.64606619e-01 7.58449912e-01 7.23875165e-01
     1.07090831e-01 4.00079012e-01 5.80695033e-01 3.60834360e-01
     1.05580091e-01 4.05367613e-02 7.76226163e-01 3.17516327e-01
     1.04784966e-04 1.17248058e-01 2.56348014e-01 6.97906137e-01
     2.59928346e-01 4.51119900e-01 7.48329878e-01 2.76349902e-01
     1.87450051e-01 6.10051155e-01 7.22780108e-01 4.25463557e-01
     2.61407495e-01 5.91025352e-02 9.33770061e-01 4.00319695e-01
     8.02669764e-01 7.17010498e-01 6.66941166e-01 1.12154603e-01
     8.32442760e-01 7.39333749e-01]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)
the shape of the tensors is: (1, 1, 1, 1, 50)
the dimensions of the tensors is: 5


In [20]:
# now squeezing the above tensors 
squeezed_tensors=tf.squeeze(tensors_1)
print(squeezed_tensors)
print('the shape of the squeezed tensors is:',squeezed_tensors.shape)
print('the dimensions of the sqeezed tensors is:',squeezed_tensors.ndim)

tf.Tensor(
[8.39977026e-01 6.16283536e-01 8.56459022e-01 1.86221480e-01
 3.53955030e-02 9.65633988e-01 5.95039606e-01 7.78796554e-01
 2.20869184e-01 8.08609366e-01 2.16290355e-01 5.07235289e-01
 2.81568289e-01 4.80004430e-01 4.65334892e-01 7.84289122e-01
 5.13068557e-01 3.64606619e-01 7.58449912e-01 7.23875165e-01
 1.07090831e-01 4.00079012e-01 5.80695033e-01 3.60834360e-01
 1.05580091e-01 4.05367613e-02 7.76226163e-01 3.17516327e-01
 1.04784966e-04 1.17248058e-01 2.56348014e-01 6.97906137e-01
 2.59928346e-01 4.51119900e-01 7.48329878e-01 2.76349902e-01
 1.87450051e-01 6.10051155e-01 7.22780108e-01 4.25463557e-01
 2.61407495e-01 5.91025352e-02 9.33770061e-01 4.00319695e-01
 8.02669764e-01 7.17010498e-01 6.66941166e-01 1.12154603e-01
 8.32442760e-01 7.39333749e-01], shape=(50,), dtype=float32)
the shape of the squeezed tensors is: (50,)
the dimensions of the sqeezed tensors is: 1


### OneHotEncoding of the tensors

In [10]:
list=tf.constant([2,3,4,5])
tf.one_hot(list,depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#one hot with custom value
tf.one_hot([0, 1, 2], depth=3, on_value=5, off_value=-1)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, -1, -1],
       [-1,  5, -1],
       [-1, -1,  5]], dtype=int32)>

### some mathematical operation in tensor

In [12]:
#creating new tensors
numbers=tf.range(1,10)
numbers

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [14]:
#square
tf.math.square(numbers).numpy()

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [17]:
#squreroot
tf.math.sqrt(numbers)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [16]:
#squreroot
tf.math.sqrt(tf.cast(numbers,dtype=tf.float32)).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>>

In [18]:
#log
tf.math.log(numbers)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log] name: 

In [19]:
#logs
tf.math.log(tf.cast(numbers,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor and Numpy

In [21]:
#create a tensor directly with numpy array
import numpy as np
tn=tf.constant(np.array([3,5,6,9]))
tn

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 5, 6, 9])>

In [25]:
#convert tensor to numpy
print(np.array(tn))
print(type(np.array(tn)))

[3 5 6 9]
<class 'numpy.ndarray'>


In [27]:
#convert tensor tn into numpy array
tn.numpy(),type(tn.numpy())

(array([3, 5, 6, 9]), numpy.ndarray)

In [28]:
#the default types of each are slightly different
tensor_from_numpy=tf.constant(np.array([3,6,7,8]))
tensor_from_tensor=tf.constant([3,0,8,6])
print('the dtypes of tensor_from_numpy is:',tensor_from_numpy.dtype)
print('the dtypes of tensor_from_tensor is:',tensor_from_tensor.dtype)

the dtypes of tensor_from_numpy is: <dtype: 'int64'>
the dtypes of tensor_from_tensor is: <dtype: 'int32'>
